# 网站标题
title: Sujay
# 网站标题后缀
suffix: Sujay
# 作者名称(会显示在首页文章下面)
author: Sujay
# 首页简介（显示在首页顶部Logo的那句话）
home_describe: 只 要 思 想 不 滑 坡 , 办 法 总 比 困 难 多
# 网站关键字
keyword: Sujay
is_article_img: true  #false是否开启文章背景图显示(随机图片)
# 网站描述
web_description: Sujay的博客
# 导航名称
menus_title:
  home: HOME
  archive: ARCHIVE
  categories: CATEGORIES
  tags: TAGS
  links: LINKS
  about: ABOUT
# 导航 （不建议修改）
menus:
  home: /
  archive: /archives
  categories: /categories
  tags: /tags
  links: /links
  about: /about
  
# logo
logo: /image/favicon.ico
# 网页标签上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面上面的图表
topIcon:
  homeIcon: "/image/favicon.ico"
  archivesIcon: "/image/archive.svg"
  tagIcon: "/image/tag.svg"
  linksIcon: "/image/links.svg"
  categoriesIcon: "/image/categories.svg"
  
# 标签页显示多少个标签
tagsNum: 1000
# 网页访问统计
web_analytics:  
  enable: false #需要改为true
  baidu: 4b5fe1472f22fa  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'Github',
    #图标    
    iconLink: '/image/github.svg',
    #跳转链接    
    toUrl: 'https://github.com/fxbsujay'
  }
# 友情链接
linksList:
  - {
    title: 'Sujay',
    intro: '收藏回忆与分享技术的地方',
    link: 'https://github.com/fxbsujay',
    image: '/image/favicon.ico'
  }
# 文字内点击图片放大相关配置
picture:
  # 蒙版的颜色也就是 打开图片背景 显示的颜色
  colour: '#333'
  # 透明度
  opacity: 0.5
  # 图片角度 就是显示图片的角度
  imgRadius: "10px"
#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
default_cover: https://api.ixiaowai.cn/gqapi/gqapi.php